# Generated by Django 4.0.4 on 2022-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_honeypot', '0003_hashcashmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashcashmetadata',
            name='bits',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashcashmetadata',
            name='salt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='hashcash_stamp',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
