# Generated by Django 4.0.4 on 2022-05-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_honeypot', '0004_hashcashmetadata_bits_hashcashmetadata_salt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashcashmetadata',
            name='bits',
            field=models.IntegerField(verbose_name='bits'),
        ),
        migrations.AlterField(
            model_name='hashcashmetadata',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address'),
        ),
        migrations.AlterField(
            model_name='hashcashmetadata',
            name='is_used',
            field=models.BooleanField(verbose_name='is used'),
        ),
        migrations.AlterField(
            model_name='hashcashmetadata',
            name='salt',
            field=models.CharField(max_length=255, verbose_name='salt'),
        ),
    ]
