# Generated by Django 4.0.4 on 2022-05-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    def create_preferences(apps, _):
        Preferences = apps.get_model('admin_honeypot', 'Preferences')
        Preferences.objects.create(
            has_fail2ban_log=False,
            bits_to_increase=2,
            salt_length=8,
            hashcash_validity_in_minutes=5
        )

    dependencies = [
        ('admin_honeypot', '0006_preferences_alter_loginattempt_hashcash_stamp'),
    ]

    operations = [
        migrations.RunPython(create_preferences)
    ]
