# Generated by Django 4.0.4 on 2022-06-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_honeypot', '0007_auto_20220516_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeUser',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('password', models.TextField(verbose_name='password')),
                ('salt', models.CharField(max_length=255, verbose_name='salt')),
            ],
        ),
    ]
