# Generated by Django 4.0.6 on 2022-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_honeypot', '0009_alter_fakeuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='hashcash_stamp',
            field=models.CharField(default='', max_length=255, verbose_name='hashcash stamp'),
            preserve_default=False,
        ),
    ]
