# Generated by Django 4.0.6 on 2022-07-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_honeypot', '0010_alter_loginattempt_hashcash_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='hashcash_stamp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hashcash stamp'),
        ),
    ]
